name: oba0
description: oba-app-0

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  provider: ^3.1.0
  qrscan: ^0.2.17
  http: ^0.12.0
  equatable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  google_sign_in: ^4.0.7


flutter:
  uses-material-design: true
  assets:
     - assets/boba_banner.png
     - assets/oba_pink.png
     - assets/oba.png
     - assets/boba_rating.png
     - assets/boba_pic.jpeg